<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fullscreen-button</name>
   <tag></tag>
   <elementGuidId>487b4a55-e2c3-4871-85b1-aa0e86cb2323</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;movie_player&quot;]/div[34]/div[2]/div[2]/button[7]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;movie_player&quot;]/div[34]/div[2]/div[2]/button[7]</value>
   </webElementXpaths>
</WebElementEntity>
